[tox]
minversion = 4.0
envlist = docs
skipsdist = true

[testenv]
basepython = python3
deps =
    -r{toxinidir}/doc/requirements.txt

[testenv:docs]
description = HTML 문서를 빌드한다 (경고를 오류로 처리).
commands =
    sphinx-build -W --keep-going -b html doc/source doc/build/html
